CREATE TABLE ms_users (
    id NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username  VARCHAR2(20) NOT NULL,
    password    VARCHAR2(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT user_pk PRIMARY KEY ( id )
);



CREATE TABLE ms_savings (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id  VARCHAR2(20) NOT NULL,
    saving    NUMBER NOT NULL,
    CONSTRAINT saving_pk PRIMARY KEY ( id )
);



CREATE TABLE tx_history (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    actor  VARCHAR2(20) NOT NULL,
    action    VARCHAR(50) NOT NULL,
    time VARCHAR(30) NOT NULL,
    deskripsi VARCHAR(70) NOT NULL,
    info VARCHAR(10) NOT NULL,
    CONSTRAINT history_pk PRIMARY KEY ( id )
);



CREATE OR REPLACE TRIGGER tx_history_on_insert
BEFORE INSERT ON tx_history
FOR EACH ROW
BEGIN
:NEW.time := TO_char(sysdate, 'YYYY-MM-DD HH24:MI:SS');
END;



CREATE OR REPLACE TRIGGER ms_saving_sync
AFTER INSERT ON ms_users
FOR EACH ROW

BEGIN
        INSERT INTO ms_savings (user_id, saving) values (:new.id,20000);     
END;

CREATE OR REPLACE TRIGGER ms_saving_warning
AFTER UPDATE ON ms_savings
FOR EACH ROW

BEGIN
    IF :new.saving < 20000 THEN
        INSERT INTO tx_history (actor, action, deskripsi, info) values (:new.id,'WARNING','Your Saving Less Than Rp.20,000', 'Success');
    END IF;
END;
